using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bookings.Domain.Entities;

public class VillaNumber
{
    //By default this if we add this key option the it will be in identity , so it will be auto generated by the database
    // but we dont want that we want to create the villa number so we should explicitely mention that the database generated is none
    [Key,DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Display(Name = "Villa Number")]
    public int Villa_Number { get; set; }

    //This specifies that villaId is a foreign key that has the reference from the primary key of the villa entity.
    [ForeignKey("Villa")]
    public int VillaId { get; set; }
    //this is the navigation property , this allows to navigate to the related villa entity directly when working with teh instance of the class
    //This is depricated
    // [ValidateNever]
    public Villa Villa { get; set; }
    public string? SpecialDetails { get; set; }
}